### ISSUE TITLE
Tags not working in CLI 

### ISSUE THREAD

**Issue by executeautomation** [dart-ogurets/OguretsFlutter#1]
Dear @rvowles,

I tried running the test with tags and its not working in CLI.

This makes all our test being skipped as shown below

`INFO: 2019-07-02 11:24:40.804158: Skipping feature F due to tags not matching
INFO: 2019-07-02 11:24:40.812464: Skipping feature E due to tags not matching
INFO: 2019-07-02 11:24:40.814636: Skipping feature C due to tags not matching
INFO: 2019-07-02 11:24:40.818164: Skipping feature D due to tags not matching
INFO: 2019-07-02 11:24:40.819708: Skipping feature A due to tags not matching
INFO: 2019-07-02 11:24:40.821453: Skipping feature B due to tags not matching
==================
Features passed: 6
`

I have also called the tags here in the code

`void main(args) async {
  var def = new OguretsOpts()
    ..feature('test_driver/features')
    ..tags("smoke")`

But still no luck

Thanks,
Karthik KK

**Comment by rvowles** [comment]
This is an issue with Ogurets rather than ogurets flutter.

**Comment by executeautomation** [comment]
Great !
