### ISSUE TITLE
Is the support of "integration_test" package is planned ?

### ISSUE THREAD

**Issue by Stephane99** [dart-ogurets/OguretsFlutter#14]
Hi,

In decembre 2020, Google advised using "integration_test" to perform integration tests:
https://flutter.dev/docs/cookbook/testing/integration/introduction
"The integration_test package is now the recommended way to write integration tests."

Is it planned to support it?

**Comment by rvowles** [comment]
No as you cannot use dynamic invocation in flutter itself, it is not possible to support integration_test
